--- 
title: "Starting Out with R and Shiny"
author: "Oliver Keyes"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: packages.bib
biblio-style: apalike
link-citations: yes
github-repo: ironholds/simpler
description: "This is a booklike set of lesson plans on starting out with R, with the goal of writing Shiny dashboards."
---

# Preamble {-}
Welcome to *Starting Out with R and Shiny*, a guide to learning basic R and ending up with the ability to put together [Shiny dashboards](https://rstudio.github.io/shinydashboard/) - online, R-based dashboards and visualisations.

This document is being written for a set of lectures in Springfield, IL, and is primarily aimed at attendees, but it will hopefully be useful to others too. It contains (or will contain):

1. An introduction to the R programming language and its history and structure;
2. A basic guide to RStudio and online help resources for questions, bugs or commentary;
3. Importing data into R from databases or flat files;
4. Cleaning and reshaping that data with tidyr, dplyr, stringr, lubridate and related tools;
5. Shiny as a data visualisation platform.

It's not intended to be exhaustive - instead the plan is to treat it as a baseline and template that people can refer back to, and fill in the gaps on the day.
